name: ci
on:
  push:

env:
  HUSKY: 0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.nvmrc }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.1
      - id: pnpm
        run: echo "::set-output name=cache-dir::$(pnpm store path)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm.outputs.cache-dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - run: pnpm install --frozen-lockfile

      - name: Run checks
        run: |
          pnpm type
          pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.nvmrc }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.1
      - id: pnpm
        run: echo "::set-output name=cache-dir::$(pnpm store path)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm.outputs.cache-dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - run: pnpm install --frozen-lockfile

      - name: Run test
        run: pnpm test:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.nvmrc }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.1
      - id: pnpm
        run: echo "::set-output name=cache-dir::$(pnpm store path)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm.outputs.cache-dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm build