name: Lint
on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter:
          - eslint
          - stylelint
          - prettier
          - tsc
    steps:
      - uses: actions/checkout@v3
      - uses: shun-shobon/actions/setup-node@master
        with:
          node-version: "lts/*"

      - name: Run test
        run: yarn test:ci
